# Generated by Django 4.0.3 on 2022-04-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_Tabla_Tareas_Descripcion_Nulleable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
